[server]
host = "0.0.0.0"
port = 8000

[database]
source = "mysql+pymysql://<username>:<password>@<host>:<port>/<database_name>"
pool_timeout = 15
pool_size = 20
connect_timeout = 60
pool_recycle = 3600

[jwt]
secret_key = "secret_key"
expiration_time = 604800

[oss]
endpoint = "<host>:<port>"
access_key = "access_key"
secret_key = "secret_key"

[gpt]
api_key = "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"
proxy = "http://127.0.0.1:7890"
