# Generated by the protoc-gen-http-python protocol compiler plugin. DO NOT EDIT!
"""HTTP server classes corresponding to protobuf-defined services."""
from typing import Callable as _Callable, Any as _Any, Dict as _Dict


_RegisterFunction = _Callable[[str, str, _Callable[[_Dict[str, _Any], bytes], _Any]], _Any]
_RequestDeserializerFunction = _Callable[[_Any, bytes], _Any]
_ResponseSerializerFunction = _Callable[[_Any], _Any]
